
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "poetry"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
  
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    open-pull-request-limit: 10
    cooldown:
      default-days: 7
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "github-actions"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
