name: Create Release
on:
  push:
    branches:
      - master
      - feature/axkr1-NRL-1544-automatic-build-artifacts  # TODO: revert to master after testing

jobs:
  create_release:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This causes all history to be fetched, which is required for calculate-version to function

      - name: Install Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Upgrade python pip
        run: python -m pip install --upgrade pip

      - name: Install git
        run: pip install gitpython

      - name: Install semver
        run: pip install semver

      - name: Set SPEC_VERSION env var
        run: echo ::set-env name=SPEC_VERSION::$(python scripts/calculate_version.py)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Create release (master only)
        id: create-release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test-${{ env.SPEC_VERSION }}
          release_name: test-${{ env.SPEC_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: make install-node

      - name: Run publish
        run: make publish

      - name: Upload documentation asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/nrl-consumer-api.json
          asset_name: nrl-consumer-api.json
          asset_content_type: application/json

